pipeline {
    agent any
    tools {
        maven 'maven'
        jdk 'java'
    }
    stages {
        stage('Build') {
            steps {
                sh '''
                    mvn clean install
                '''
            }
        }
        stage('Archive') {
            steps {
                dir('target') {
                    archiveArtifacts '*.jar'
                }
            }
        }
    }
}

